version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # PostgreSQL connection strings
      - TRADES_DB_URL=postgresql://trader:xyz@host.docker.internal:5432/trades

      - MARKET_DB_URL=postgresql://marketmaker:xyz@host.docker.internal:5432/market
    # Map host.docker.internal to the Docker host on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
