version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # PostgreSQL connection strings
      - TRADES_DB_URL=postgresql://trader:xyz@localhost:5432/trades
      - MARKET_DB_URL=postgresql://marketmaker:xyz@localhost:5432/market
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3 
