import { NextResponse } from "next/server"
import fs from 'fs'
import path from 'path'

export async function GET(request: Request) {
  try {
    // Path to the JSON file generated by the Python script
    const jsonPath = path.join(process.cwd(), 'public', 'trade_metrics.json')
    
    // Check if the file exists
    if (!fs.existsSync(jsonPath)) {
      return NextResponse.json(
        { 
          success: false, 
          error: "Trade metrics data not found. Please run the Python script first." 
        },
        { status: 404 }
      )
    }
    
    // Read the file
    const fileContents = fs.readFileSync(jsonPath, 'utf-8')
    const data = JSON.parse(fileContents)
    
    // Return the data
    return NextResponse.json(data)
  } catch (error) {
    console.error("Error reading trade metrics data:", error)
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : "Unknown error occurred" },
      { status: 500 }
    )
  }
} 